### ISSUE TITLE
3.2 compatibility

### ISSUE THREAD

**Issue by designerontherun** [ArmoredColony/ARMORED-Toolkit#1]
Was having a quick play with 3.2 and there seem to be a few issues with select through now that they've taken away tweak mode, is there an easy way to fix via keymap? Also noticed that modal primitives produce an 'nonetype' attribute error.

**Comment by ArmoredColony** [comment]
Hello, thanks for reaching out.

I actually removed the Select Through script a long time ago because I didn't like how it was scripted. Might re-create a better version of it someday but it's not part of the addon at the moment, sorries for that one.

Thanks for bringing the modal primitives bug to my attention. That's probably an easy fix. I will install the blender 3.2 beta tomorrow and see what it's about.

Good day, colonist.

__
www.armoredcolony.com
www.youtube.com/armoredColony

**Comment by designerontherun** [comment]
Oh is see no worries! Thanks for your add-on, I use it all the time :)

**Comment by ArmoredColony** [comment]
Alright, I got distracted playing an Elden Ring co-op mod I found but I finally got around fixing the modal primitives issue.

**Comment by designerontherun** [comment]
Too awesome, thanks!
