### ISSUE TITLE
Buggy with 3.41

### ISSUE THREAD

**Issue by pokeslog** [ArmoredColony/ARMORED-Toolkit#2]
Trying to just use Connect through F3 and it seems to work some times but not all the time.   I haven't tried Blender 3.5 yet.   I know you've been working on your web store.

**Comment by ArmoredColony** [comment]
Hello, thanks for reaching out.

Can you double check you're running the correct script? "ARMORED Connect",
because there are other operators with the same name in the search menu (F3)

If that is not the problem, can you show me a screenshot of your
selection and another screenshot of what happens after you run the script?
